\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{lab}

\LoadClass{article}

% Czcionki i język polski
\RequirePackage[utf8]{inputenc}
\RequirePackage[polish]{babel}
\RequirePackage[T1]{fontenc}

% Pozycjonowanie rzeczy
\RequirePackage{adjustbox}
\RequirePackage{float}
\RequirePackage{wrapfig}

% Tabelki
\RequirePackage{multicol}
\RequirePackage{multirow}
\RequirePackage{booktabs}
\RequirePackage{tabularx}
\RequirePackage{longtable}

% Grafika
\RequirePackage{graphicx}

% Pisane rzeczy
\RequirePackage{caption}
\RequirePackage{listings}
\RequirePackage{comment}
\RequirePackage[colorlinks, linkcolor=black]{hyperref}

% Matematyka
\RequirePackage{amsmath}

% Fizyka
\RequirePackage{siunitx}
